### PR TITLE
Advanced option: do not use bridging infill above a specified fill density

### PR DESCRIPTION
**Pull request by lordofhyphens**
Addresses #1986 #3483
If someone can think of a good auto test for this I'd be appreciative of it. I verified it by looking at the output for the generated layers (visually).

### CODE REVIEW

**Comment by lordofhyphens** [comment]
Not breaking existing expectations.

**Comment by bubnikv** [comment]
This is certainly a good thing. Another extension would be to make the bridging sparse. This is what the kisslicer does.

Now we are getting more and more configuration values, which makes the UI cluttered. The "new" cura handles the UI clutter by a configuration of configuration UI. I wonder where Slic3r is going in this regard.

**Comment by alexrj** [comment]
I had actually addressed this issue in 38a9e32a287c4a601e256ebd96533f68c0c8dcc0 (after this issue reports), and I have one more improvement for making this logic even stricter.

**Comment by alexrj** [comment]
I'm proposing an alternative thing in #3627, comments very welcome.

**Comment by lordofhyphens** [comment]
Alternative merged, closing :)

**Pull request closed without merging**
