### PR TITLE
Windows 32-bit build.

### PR DESCRIPTION
**Pull request by lordofhyphens**
Reworked Windows build scripts to produce 32bit and 64bit builds.

### CODE REVIEW

**Comment by alexrj** [comment]
Wow. Lots of work into this.
(I only see a 64bit build in /dev/win though)

**Comment by lordofhyphens** [comment]
Just saw that the build is registering as failing due to 2 failing tests.
It has been passing in the branch.

https://ci.appveyor.com/project/lordofhyphens/slic3r/build/job/qnqfox8ru5nv7xak

**Comment by lordofhyphens** [comment]
It may be because of an old XS dll polluting things, actually.

**Comment by lordofhyphens** [comment]
I've uploaded a new local-lib without Slic3r's own XS in it, should avoid
false positives and a clean Boost build. I built Slic3r locally using this
Boost beforehand.

https://ci.appveyor.com/project/lordofhyphens/slic3r/build/job/w47lkbr9f6ofkbbl

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by lordofhyphens** [comment]
Builds, but missing a dll that OpenGL calls.

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Pull request merged**
