### PR TITLE
Solarized Color Scheme

### PR DESCRIPTION
**Pull request by foreachthing**
Added an optional color scheme ([solarized](http://ethanschoonover.com/solarized)) to Slic3r.
See option in `Files` -> `Preferences` -> `Color Scheme`.

image

image

image

image

### CODE REVIEW

**Comment by lordofhyphens** [comment]
I'm down with merging this.

**Comment by lordofhyphens** [comment]
I'm down with merging this.

**Comment by lordofhyphens** [comment]
Can you open a PR against Slic3r-Manual talking about this option?

**Comment by foreachthing** [comment]
Thanks for the merge! 
Will update the manual soon.

**Pull request merged**
