### PR TITLE
Infill strategy for laser printing (SLS SLA)

### PR DESCRIPTION
**Pull request by veneridesign**
Should be important have the option to use a filling strategy for laser  Beam based printers like SLS or SLA, these printers dont have the  Ooze problems crossing perimeters but the action to leave the infill operation localy to start in another point and then come back it's letal for the correct power distribution of the ray on the surface.Best option a simply scansion that start from one direction to finish in the opposite direction.
Thankyou

### CODE REVIEW

**Comment by lordofhyphens** [comment]
Um, is this actually a pull request (you have code you want to contribute
to Slic3r) or a feature request (you have a want for new features in
Slic3r)?

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by lordofhyphens** [comment]
I see you already have a feature request as issue #2802, was this pull request supposed to be able to fix that issue? 

If not, please don't open up pull requests asking for features. Pull requests are for you to try to contribute your code.

**Comment by veneridesign** [comment]
Yes, it's related to that issue, so coming back to the topic ....any tips? There are already parameter in the code to change the paths planning behavior?

**Comment by alexrj** [comment]
This doesn't look like a proper pull request, so let's please stick to #2802.

**Pull request closed without merging**
