### PR TITLE
Fix perl redefining multiple functions used by boost

### LINKED ISSUE #3583: latest changes: cant compile under windows
### Version
latest version

### Operating system type + version
win10 64

### Behavior
An hour ago, I issued the normal GIT PULL, PERL BUILD.PL commands
In the build i get to this point:
t\22_config.t ................... ok

And it stays there for ever. I gave it like 15 minutes and just stayed there.
The git pull I did 1 week ago apart from the opengl problem, builded with no problems.

### PR DESCRIPTION
**Pull request by lordofhyphens**
Should fix remaining compile issues on Windows.

Fixes #3583

### CODE REVIEW

**Comment by Tinchus2009** [comment]
Sorry to report this :(. But there is still somenting wrong with the compilation under win 10 64.
The build goes ok till it gets here:

t\22_exception.t ................

and it stays there forever (to be fare I waited 20 minutes, I guess that is enought time)

**Comment by lordofhyphens** [comment]
That means your Perl is 64 bit and "broken". Use 5.18 64 bit or 5.24 32bit.

**Comment by lordofhyphens** [comment]
That rest really needs some kind of timeout so that it dies and fails
rather than hanging out forever.

**Comment by Tinchus2009** [comment]
ok.... but Im useing Strawberry Perl (5.22.1.3-64bit), it was working perfectly with the lasts buildsfrom 2 weeks ago. Originally I was useing 5.18 indeed but with a compilation error that happend like 2months ago, I was told to move to this version jajajajajaja

**Comment by lordofhyphens** [comment]
That test was added in the last two weeks. Use the -32bit perl (it runs
just fine on 64 bit windows) until I figure out how to deal with timeouts.

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by Tinchus2009** [comment]
Nope... perl 32 does not run on win 10 64bit

**Comment by lordofhyphens** [comment]
Yes it does, because that's what my setup is on my development windows
system. Perl 5.22 32-bit strawberry perl.

Also, your report of the test hanging forever is completely unrelated to
this PR.

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by Tinchus2009** [comment]
Oh, sorry, I go back to #3583 then. Compilation still fails: seing perl 32 bits and useing perl 5.18 64 bit also. I post details in the original thread then

**Comment by bubnikv** [comment]
> but Im useing Strawberry Perl (5.22.1.3-64bit), it was working perfectly
with the lasts buildsfrom 2 weeks ago.

It did not work perfectly. Some of the hang-ups you may have experienced
were caused by the broken Perl. For example, try to run the sequential
printing.

**Comment by Tinchus2009** [comment]
I was not talking about slicer, I was talking about the building of it

**Pull request merged**
