### PR TITLE
OctoPrint SD card upload option

### PR DESCRIPTION
**Pull request by quillford**
Added SD card upload for OctoPrint users.

### CODE REVIEW

**Comment by lordofhyphens** [comment]
How does this differ from send gcode to printer that is already available?

**Comment by quillford** [comment]
It allows the gcode to be uploaded to an SD card on your printer, so that if something happens to OctoPrint it will keep printing.

**Comment by lordofhyphens** [comment]
That seems to be the case already with my octoprint install and the send
gcode

**Comment by alexrj** [comment]
Thank you for the pull request. I have a couple comments: option names never have uppercase characters or camelCase style, so I'd rename that to `octoprint_loc` for coherence. Second: your text editor changed a lot of whitespace lines, so this ends up to a huge dirty patch which is not good.
But nevermind, I can hand edit the change and add the option myself.

I wish Octoprint had a default location setting and we could just call `POST /api/files` without storing yet one more config option...

**Comment by quillford** [comment]
I fixed the variable names. Onto whitespace ;-)

**Comment by quillford** [comment]
I don't really have a need for this anymore and it's pretty easy to implement if you want to do it, so I'll close this pr.

**Pull request closed without merging**
