### PR TITLE
Master

### PR DESCRIPTION
**Pull request by a4jp-com**
Please add this exe like file to open the compiled files easily and also the icon.

### CODE REVIEW

**Comment by alexrj** [comment]
Sorry, I'm not going to add any binary executable file to the repository. Keep these files in your local repository if you want to use them.

**Comment by a4jp-com** [comment]
Okay but they are so useful to load the program. I will keep them in my version. Thank you for the great updates to Slic3r recently. The speed of loading files has improved a lot too ^^

**Comment by lordofhyphens** [comment]
A windows lnk makes no sense, as the path is encoded in there anyway.

**Comment by a4jp-com** [comment]
Okay. ^^

**Pull request closed without merging**
