### PR TITLE
Implemented configurable width for skirt lines.

### PR DESCRIPTION
**Pull request by lordofhyphens**
This is useful for priming skirts.
Also added functions to Slic3r::Flow() to calculate spacing and mm3_per_mm for alternate flow widths (as trying to generate an new one crashed slic3r).
Addresses #1333.

### CODE REVIEW

**Comment by lordofhyphens** [comment]
@starno this PR does need more testing before it can make it in, so if you've got the time, please test it.

**Comment by alexrj** [comment]
Wait before merging this. Thank you

**Comment by alexrj** [comment]
I disagree with this. Seems overkill and not really addressing the reported issue. See my comments in #1333

**Comment by lordofhyphens** [comment]
Associated issue is closed.

**Pull request closed without merging**
