### PR TITLE
Added Repetier-Server upload functionality

### PR DESCRIPTION
**Pull request by miked63017**
I know not everyone cares for Repetier or Repetier-Server, but I kinda like it. It was a hassle for me to go through the web browser to upload all the time so I added the functionality to do it from Slic3r. Its really similar to the octoprint upload code, in fact most of it was copied and pasted then updated, but hey that code works so why start from scratch :)

### CODE REVIEW

**Comment by alexrj** [comment]
AFAIK, Repetier-Server is not an open source project anymore. I don't think Slic3r should support commercial products with specific built-in features, especially when such products are not widely used. The same functionality could be still achieved by crafting a post-processing script that performs the upload.
I still appreciate your contribution.

**Comment by miked63017** [comment]
@alexrj AFAIK it is still open source, sorry I missed your reply BTW. https://github.com/repetier/Repetier-Server he is still answering issues and what not on the github, though there hasn't been a commit in a while. You could be right, but maybe there is 2 project, one open and one not idk. Either way it is a nice feature to have, to be able to upload to the server directly. Let me know if you still disagree, if so I will close this.

**Comment by lordofhyphens** [comment]
@alexrj any change of opinion about this?

**Comment by cbusillo** [comment]
Will this get updated to work on 1.3.0.  I would be interested in Slic3r if it could print directly to Repetier Server.

**Comment by miked63017** [comment]
FWIW since repetier-server blocked some functionality unless you are on the paid version I have stopped using it and went to octoprint. I will not be updating this branch, and I actually meant to close this since @alexrj did not want to merge it. Closing...

**Pull request closed without merging**
