### PR TITLE
Background slice now

### LINKED ISSUE #3071: FEATURE REQUEST: Add a "Slice now" button
Using Slic3r on a daily basis, I often have to change many settings for specific print jobs, which trigger the background slicing every time. On larger pieces, it crashes the engine when changing the options and the background slicing has not completed it's run.

My request would be to have a "Slice Now" action button so you can disable background slicing and manually trigger the slicing, see the preview and make adjustments. I know you can export the GCode to trigger the slicing but exporting the GCode is unnecessary for me since I send it the the OctoPrint server (which is a very nice feature btw).

Thanks for the consideration.

### PR DESCRIPTION
**Pull request by lordofhyphens**
Fixes #3071

### CODE REVIEW

**Comment by lordofhyphens** [comment]
Win32 build will appear at https://bintray.com/lordofhyphens/Slic3r/Slic3r_Branches

**Comment by bubnikv** [comment]
The patch is fine, I have two comments though:
1) The new button shall be hidden if the background processing is enabled. The button has no meaning then, as the background processing triggers automatically anyway.
2) The button avoids crashes if the background processing triggers when a value is entered into the Slic3r confugration fields only partially. But the button causes Slic3r crash in many cases the same way Slic3r crashes with the background processing enabled, which defeats the purpose of the button. So the idea is sound, but we should concentrate on fixing the background processing crashes.

**Comment by bubnikv** [comment]
Thanks, I extended your implementation
https://github.com/prusa3d/Slic3r/commit/34fab1566f7a99dd40d9856cb5185c8d20d1ddec
Namely, we added an image to the button and we hide the button when the background processing is enabled. Also we allow the "cancel" button on the status bar.

**Comment by lordofhyphens** [comment]
I've pulled the extended implementation into this PR, so it can be merged now.

**Comment by alexrj** [comment]
Merged!  (I ignored the changes to xs/src/libslic3r/PrintConfig.cpp while merging).

**Comment by alexrj** [comment]
Hm. I still want to try the other way described in #2979, without a button.

**Pull request merged**
