### PR TITLE
Fix of git #3293: More efficient GCode export

### PR DESCRIPTION
**Pull request by lordofhyphens**
This fixes two problems of repeatedly copying data from the C++ layer
to perl, by factoring the copying out of an inner loop.

Actually done by @bubnikv. I cherry-picked the commit out of his rc 1.3 branch from the prusa3d repo.

Addresses #2790

### CODE REVIEW

**Comment by lordofhyphens** [comment]
https://github.com/alexrj/Slic3r/files/336282/slic3r-most_prs.zip this PR is in this, please test and provide feedback

**Comment by lordofhyphens** [comment]
#2790 should be mostly addressed by this PR as well.

**Comment by Martronic-SA** [comment]
I've had the same problem and it took me some time to understand that it was coming from "Avoid crossing permeters"
That feature sounds great but it has to be optimised! It seems that for the path calculation it's taking the point that is the most far away from all the surrounding permieters instead of going in straight lines.
The result is the nice path in red in the picture below:

This is nice but not optimised at all! Very long to generate, huge output file and also 2-3 times printing duration.

**Comment by lordofhyphens** [comment]
The general 2d routing problem is NP Complete, IIRC. There is no optimal
solution available that doesn't take exponential time (or space).

If someone  can work out a better heuristic for the average case but there
will always be corner cases that take forever.

**Comment by kefir-** [comment]
Perhaps "avoid crossing perimeters" should be considered an advisory option, and not a requirement? That way you can make some heuristic as you say, and if it takes too long to calculate or causes some sort of troublesome move (too long, for example), just cross the perimeter instead. Or lift instead?

**Pull request merged**
