### PR TITLE
Octoprint settings functionality expanded to allow upload to RepRapFi…

### PR DESCRIPTION
**Pull request by emaker**
…rmware on a Duet controller.
Some way towards solving #4022 although I don't know about any other print servers at this time.

### CODE REVIEW

**Comment by emaker** [comment]
I wasn't sure how to implement the aliases you mentioned, so I added octoprint_host as a legacy option in PrintConfig.cpp, using the Bed_Size option as a guide.

**Comment by lordofhyphens** [comment]
Looks good, thanks for the commit. This looks generic enough that if someone wants to continue to add support for another host program that doesn't need more than what is provided we're still good to go.

**Comment by lordofhyphens** [comment]
If it needs a refactor for the next one, then we'll deal with it then.

**Comment by rob-miller** [comment]
This is great to have (!!!) 
But on 1.18.1 DuetWifi Slic3r automated build slic3r-1.3.0-dev-98fca90.dmg I find:
- if the file does not exist on the SD card already, Duet reports 
'GCode file "lsm1.gcode" not found
Failed to open file lsm1.gcode'
(or whatever file may be called)
- if a file with the same name exists, the existing file is queued for printing (but not the new one sent from slic3r)

this is with 'Overwrite existing file' and 'Start print' enabled.  Have tried other settings, all consistent with not getting file loaded on to SD card.

**Comment by emaker** [comment]
@rob-miller I don't have a DuetWifi to play with, but this code was developed using a Duet 0.6 over ethernet, and with @chrishamm's firmware 1.18-b2. I didn't test with 1.19 as it didn't appear to be stable yet.

**Comment by rob-miller** [comment]
Thanks, saw that on the duet forum.  Surprised the behaviour is different on mine - initially thought it worked until realised the file was the old one.  happy to debug this offline (email in my gh profile)

**Pull request merged**
