### PR TITLE
Add accelerators (keyboard shortcuts) to View menu

### PR DESCRIPTION
**Pull request by xoan**
* Follow the OpenSCAD convention:
  * Reorder the items
  * Rename Rear -> Back and Iso -> Diagonal (Iso stands for a projection, not
    for a view -- upcoming versions could have isometric/prespective views...)
  * Assign accels from 4 to 0

### CODE REVIEW

**Comment by lordofhyphens** [comment]
Is this going to conflict with the gui3 branch? Could you check that
(either open a PR against it to test mergeability or on your local side)

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by xoan** [comment]
> Is this going to conflict with the gui3 branch?

No, this PR is already against `gui3` branch.

**Comment by alexrj** [comment]
Thank you!
Parking this until we merge gui3, which will happen very soon.

**Comment by lordofhyphens** [comment]
@alexrj we can certainly merge this against gui3 and then merge gui3.

**Comment by xoan** [comment]
Actually, yes. This PR should be merged into `gui3`, which is the branch my PR is compared to, and before merging upstream `gui3` into `master`.

**Comment by alexrj** [comment]
You're right, I didn't notice that.

**Pull request merged**
