### PR TITLE
Added code documentation

### PR DESCRIPTION
**Pull request by lordofhyphens**
Addresses #3579 
Thanks to @bubnikv ! 

The difference from the related commit in 620c6c7378c4799980f63794669548c104b9bcea is that this contains the comments only.

### CODE REVIEW

**Comment by lordofhyphens** [comment]
I've read over the comments that were added and they look relatively straightforward. Since the only changes are in comments/docs, I am merging them in (squash merge to make it simple to revert if necessary).

**Comment by alexrj** [comment]
I merged those four commits manually. Thank you!

**Comment by lordofhyphens** [comment]
So did you get the optimizations as well or should I continue work on
collecting those into pull requests?

**Comment by alexrj** [comment]
I merged all the four commits contained in this pull request (except for the CLIPPER_OFFSET_SCALE which I rewrote as I changed that file)

**Pull request closed without merging**
