### PR TITLE
Support moving objects using keyboard arrows in the 2d plater view.

### LINKED ISSUE #4102: feature request: support nudge in 2d plater view.
### Version

slic3r-1.3.0-dev-13f121e

### Operating system type + version

OSX  10.11.6 

### Feature Request: 

in the plater view, in 2d mode.   I would like to use the arrow keys to move the selected object 1 mm at a time.  (or configurable amount)  ie,  nudge.  

my bed is small and i'm often carefully aligning a set of parts.  this feature would make  that much easier. 

thanks for your work and your consideration.

### PR DESCRIPTION
**Pull request by Samir55**
_**Fixes #4102.**_

### CODE REVIEW

**Comment by lordofhyphens** [comment]
Any updates to this @Samir55 ?

**Comment by Samir55** [comment]
@lordofhyphens I will finish it soon :smiley: . Sorry,  I have been busy the previous month.

**Comment by Samir55** [comment]
The Keyboard Shortcuts:
* On Mac & Linux: use Arrow Keys or (W, A, S, D).
* On Windows: use (W, A, S, D) **only**. 

@lordofhyphens  I couldn't support moving instances using the arrow keys on windows, It's a focus problem. I tried to find a solution but in vain. 
Otherwise, I think it's ready to be merged.

**Comment by lordofhyphens** [comment]
Thanks. After it is merged, can you make a small commit to the Manual
describing the feature?

On Oct 8, 2017 9:17 AM, "Ahmed Samir" <notifications@github.com> wrote:

The Keyboard Shortcuts:

   - On Mac & Linux: use Arrow Keys or (W, A, S, D).
   - On Windows: use (W, A, S, D) *only*.

@lordofhyphens <https://github.com/lordofhyphens> I couldn't support moving
instances using the arrow keys on windows, It's a focus problem. I tried to
find a solution but in vain.
Otherwise, I think it's ready to be merged.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/alexrj/Slic3r/pull/4104#issuecomment-335009619>, or mute
the thread

**Comment by Samir55** [comment]
@lordofhyphens I've written a manual describing the feature in my fork [here](https://github.com/Samir55/Slic3r/wiki/2D-Plater), Under which topic shall I add it in the manual? These are the topics in the manual:
* Introduction
** Overview
** Getting Support
* Getting Slic3r
** Downloading
** Installing
** Building from source
* First Print
** Calibration
** Configuration Wizard
** The Important First Layer
** Working with Models
** Printing
* Simple Mode
** Print Settings
** Filament Settings
** Printer Settings
* Expert Mode
* Input/output files
* Topics
** Multiple Extruders
** Draft Quality
* Advanced Topics
** Command Line Usage
** Post-Processing Scripts

**Comment by lordofhyphens** [comment]
Add it to to working with models. I will move it later.

**Comment by lordofhyphens** [comment]
Sorry for not getting to that for so long, work consumed me. It's still trying to get me.

**Comment by Samir55** [comment]
No problem @lordofhyphens ;). Hope you finish that work soon 😄. I'll resume my work in here when I have some time.

**Pull request merged**
