### PR TITLE
Tweakable xy supports

### PR DESCRIPTION
**Pull request by lordofhyphens**
Added option to increase XY supports (addresses #2916 and #3298), through a new config option and adjusting the clip_with_object and the contact layer. Defaults to 0 (current behavior), and may cause weird things to happen with support generation if set high. 

May be useful to adjust the minimum span to support to include this value as well.

### CODE REVIEW

**Comment by lordofhyphens** [comment]
This should also fix #3095.

Obviously I can't guarantee it will do what you expect w/r/t support generation everywhere for all values.

**Comment by lordofhyphens** [comment]
@alexrj I'd appreciate any comments from you on this (experimental in nature) feature.

**Comment by lordofhyphens** [comment]
This would probably also fix #854 if I am reading it correctly.

**Comment by lordofhyphens** [comment]
https://github.com/alexrj/Slic3r/files/336282/slic3r-most_prs.zip

Experimental build for win32 for testing

**Comment by lordofhyphens** [comment]
#1539

**Comment by lonelymyp** [comment]
I am one of those who have had problems, but I can not compile, you have compiled file?

Error: The locale codeset (cp1251) isn't one that perl can decode, stopped at Encode/Locale.pm line 120.
Compilation failed in require at Slic3r.pm line 71.

**Comment by lordofhyphens** [comment]
@lonelymyp see link above https://github.com/alexrj/Slic3r/files/336282/slic3r-most_prs.zip

It's packaged, so I can't guarantee it'll work on all systems for all codepages.

**Comment by lordofhyphens** [comment]
@alexrj this PR is definitely experimental (as in results may not always be what is desired). If you have some interest in it as a feature I can continue to look for bugs on it.

There has been a lot of calls for better control over support generation.

**Comment by bubnikv** [comment]
Thanks @lordofhyphens for the work.

Comparing Slic3r with Simplify3D, the Simplify3D has two settings to configure the horizontal offset:
1) XY offset
2) Vertical (above / below) offset in number of layers.

Slic3r does not do 2), so even if there is a gap in the layer, it will fuse to the layer above or below AFAIK.

Another issue is the extrusion height of the bottom interface layer, which is tune for bridge flow, but extruded as normal flow. This probably leads to corners of the extrusion not sticking well enough and being dragged into a covex corner of an object.

**Comment by lordofhyphens** [comment]
@bubnikv what Slic3r does do is offset Z in mm, and it does honor it for interfaces. What it does also do, however, is enforce a minimum gap of {nozzle_width} (0 is special-cased here to avoid this), the setting in the config is actually {nozzle_width} + value, not value (as is often assumed).  There's a related PR out to change this behavior.

I haven't looked too closely at the flow attributes for the interface layers (assuming you are referring to  the furthest layer of the interface against the underside of an object, not the closest layer of support against a top surface of an object.

**Comment by lordofhyphens** [comment]
As this is a hack on the current supports and we're looking to replace them, better to not add and remove options that people will complain about ;)

**Pull request closed without merging**
