### PR TITLE
Fix to autocenter option.

### PR DESCRIPTION
**Pull request by GilesBathgate**
Ensure that with autocenter turned off the part is not positioned
in the center of the bed.

### CODE REVIEW

**Comment by lordofhyphens** [comment]
I'm okay with changing this behavior slightly, especially as autoarrange is on by default and triggering arrangement is a single click away. 

The only real concern I have is people with really idiotic STL coordinates such that they don't see it on the bed and then file bug reports against it.

**Comment by GilesBathgate** [comment]
@lordofhyphens You make a good point about the coordinates being way outside the print bed area, and thus making the geometry invisible. I think it would be appropriate for slic3r to provide a warning message when the geometry is outside the print bed, (it already provides a similar warning when its too big for the build plater). I will see if I can create a new pull request that provides a warning message.

**Comment by GilesBathgate** [comment]
@lordofhyphens I have prototyped the warning message change in https://github.com/alexrj/Slic3r/pull/4163

**Comment by lordofhyphens** [comment]
Fun fact: This broke the slab mesh positioning.

**Comment by GilesBathgate** [comment]
@lordofhyphens Damn, If you can describe the problem then I will see if I can provide a fix. Although if its the later, don't panic and have a warm relaxing cup of tea.

**Comment by lordofhyphens** [comment]
@GilesBathgate  I tried to reproduce myself and couldn't. 

If you want to look yourself, grab a model, right-click -> Settings and create a slab modifier. In my tests it wasn't centering the slab properly in XY.  And then it was, hence my wondering about my hallucinating it in the first place.

**Comment by GilesBathgate** [comment]
@lordofhyphens I think there is a change in behaviour, previously I think it would have centred the object, and the slab to the centre of the bed so they would be centre aligned. Because there is no repositioning of the part or the slab I think they can be misaligned. I think the slab should be positioned to the centre of the existing object and not to the centre of the bed or the 0,0 origin.

**Comment by GilesBathgate** [comment]
@lordofhyphens Well I have managed to fix the unintended behaviour, but I am not confident that this is the best approach. I tried creating something more robust but I couldn't get it to work. The proposed fix certainly worked in my limited test cases.

https://github.com/alexrj/Slic3r/pull/4170

**Pull request merged**
