### PR TITLE
Add Ubuntu installation instructions

### PR DESCRIPTION
**Pull request by tareko**
Add installation instructions including easy to copy-paste commands for Ubuntu apt

### CODE REVIEW

**Comment by tareko** [comment]
I always have to go back and figure out how to do this each time I try to re-compile Slic3r on a new computer, so here are my compiled directions.

**Comment by lordofhyphens** [comment]
I can't merge this, but it's feasible to add to the wiki: https://github.com/alexrj/Slic3r/wiki/Running-Slic3r-from-git-on-GNU-Linux/

I also disagree strongly with not using local::lib on Debian-based architectures, as it invariably breaks the related packages. This is been my experience time and again when building on package-based distros.

**Comment by lordofhyphens** [comment]
For Debian and Ubuntu if you don't want to use local::lib imho is to unpack the Ubuntu package source (the debian directory) for slic3r 1.2.9 over a fresh checkout of the repository, and then installing the package.

**Comment by lordofhyphens** [comment]
libwxgtx2.8-dev is also becoming rarer on modern Ubuntu distros, ran across someone who didn't have it on their xubuntu distro.

**Comment by lordofhyphens** [comment]
The good news is that this prompted me to reorganize the wiki page on building on linux. The bad news is that I'm closing this pull request because it can't be merged.

**Comment by tareko** [comment]
Thank you for doing this. I think having it in the wiki works well enough.

tarek : )

**Pull request closed without merging**
