### PR TITLE
Extended Context Menu and Toolbar for Rotating Objects

### PR DESCRIPTION
**Pull request by foreachthing**
Added 4 new Buttons to the toolbar and a bunch of rotate-commands to the context menu.

context
toolbar

### CODE REVIEW

**Comment by lordofhyphens** [comment]
That it a lot of convenience items added to that context menu for not much
gain IMHO. @alexrj?

**Comment by alexrj** [comment]
Ouch. Appreciate the contribution but those are way too many new items. I don't know any other CAD/CAM software with this abundance of shortcuts. You know, many people complain about Slic3r interface being overcrowded and I want to keep it simple.

It's better to improve the "Rotate..." dialog and put shortcuts there. Look at what Netfabb does (it's still way too complicated IMHO):

schermata 2017-03-24 a 20 11 06

(On a side note, your pull request contains tabs instead of spaces. Please use 4 spaces for any future contribution.)

**Comment by foreachthing** [comment]
Sure, no problem! :-)
In Cura or CraftWare you can rotate objects with the mouse. This would render all shortcuts useless.
Maybe the context menu could be customized...?!

**Comment by foreachthing** [comment]
>  I don't know any other CAD/CAM software with this abundance of shortcuts.

You've never seen SolidWorks, I guess? That is a mess!

**Comment by alexrj** [comment]
Haha :-)

I agree with you about visual rotation. There's an open issue for that, #3745

**Pull request closed without merging**
