### PR TITLE
Fix not generating supports

### PR DESCRIPTION
**Pull request by cangelis**
Slic3r does not generate support correctly for some models. Download an example [here](https://www.dropbox.com/s/oi2u2m2efjlzhdz/slic3r-support-not-generating-example.stl?dl=0)

`clip_with_object()` method uses wrong `$support_z` indices `$i` which are support layer heights (`$support` hash indices).

This PR fixes the `$zmax` and `$zmin` at `clip_with_object()` and apply the method only on `$contact` rather than `$interface`s and `$base`s (which are generated using `$contact`). This also improves the performance drastically on complex models. 

This PR also fixes the first interface layers' xy spacing, which was not calculated before.

### CODE REVIEW

**Comment by lordofhyphens** [comment]
Could you put a picture in of what looks wrong with the old logic with that model? I can't really see the difference myself with the provided model and my collection of settings.

A config export would also be helpful (you can upload .zip files to github).

**Comment by cangelis** [comment]
These are the screenshots of the wrong interface layer and the contact layer. Please see the [link](https://www.dropbox.com/s/g92hkojkzzeme21/config.ini?dl=0) for the config.ini file.

screen shot 2017-10-23 at 09 49 30

screen shot 2017-10-23 at 09 49 22

**Comment by cangelis** [comment]
Oh sorry this example works well on the current code. I need to find another one. I will provide as soon as I find.

The reason I encountered with the issue is that my codebase works different z-spacing for the support materials.

**Comment by lordofhyphens** [comment]
@cangelis any updates?

**Comment by cangelis** [comment]
Could not regenerate the issue. Better to close the PR until somebody encounters again!

**Comment by lordofhyphens** [comment]
Thank you for trying to reproduce.

**Pull request closed without merging**
