### PR TITLE
Added options to printer tab to manage 'Send to Printer' related dialogs

### PR DESCRIPTION
**Pull request by gege2b**
Replace PR #3751 

Moved options from plater to printer settings

One thing I don't really know how to handle is the CLI parameters (actually I leave them empty, because I don't think they make sense, but correct me if I'm wrong )

### CODE REVIEW

**Comment by lordofhyphens** [comment]
CLI parameters accessible from config are basically the same as any other
parameter (if you copypasta from another configuration item the items are
available on the CLI).


"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by gege2b** [comment]
yep! but does it make sense to have CLI parameters allowing the display of dialogs ? ;) 

That's the point of these options : allow (or not) to show dialogs when sending to octoprint, make sense in a GUI...

Note : I've never used CLI version

**Comment by lordofhyphens** [comment]
https://github.com/alexrj/Slic3r/blob/master/lib/Slic3r/GUI/Preferences.pm ?

**Comment by gege2b** [comment]
After ripping off these options from the plater, I considered adding them to the preference dialog, but it would make no sense for people who don't use Octoprint.
And we would loose the per printer settings, witch are important I think

But again, correct me if I'm wrong

Does every options presents in print/filament/printer tabs should have a CLI parameter ?

**Comment by lordofhyphens** [comment]
Not if it does not make sense from a CLI context. I don't know if assigning
the CLI option is compulsory from a code standpoint.

**Comment by alexrj** [comment]
@gege2b, I know you'll hate me and you don't agree with this. However I always try not to add too many options, and this is really overkill. The usual print/export pattern for any application is: click on button -> get one single dialog with the print/export options -> click OK.
I now merged all the options in a single dialog. I understand it's one more click, but it's exactly the same number of clicks people have to do when saving the G-code file somewhere, and it's a very common UX pattern. Much more than moving options outside of the flow.
But there's a hidden feature just for you: if you hold the Alt key when clicking on the "Send to printer..." button the dialog will not be shown (and last settings are used) :-)
Thank you for understanding.

**Comment by gege2b** [comment]
at the begining of your post yeah I kinda hate you, and then I read the ALT key cheatcode... ;) 
It's so simple... I don't know why I didn't think about it myself !

And you're wrong, I totally understand your point, and at least I tried and proposed something (and it gave me the opportunity to dig into the UI code)

so, well, thank you a lot !

**Comment by lordofhyphens** [comment]
Issue a pull request against The Manual for that information and I think I
will be able to accept it ;)

**Comment by gege2b** [comment]
OK,  will do this, later this week ^_^

**Pull request closed without merging**
