### PR TITLE
Debugging visualization of the gap fills into a SVG format, if SLIC3R…

### PR DESCRIPTION
**Pull request by bubnikv**
Alessandro,

while working on the variable gap fill (unfortunately in parallel with you), I added a debugging visualization of the Voronoi diagram and the gap fill trapezoids, based on an example from the boost::polygon library. Please consider adding it to the main branch. I believe you will find the debugging visualization useful.

Thanks, Vojtech

### CODE REVIEW

**Comment by alexrj** [comment]
Hello, can we move this to a separate file? Like Geometry_debug.cpp. I'd like to keep the main code as much clean as we can, without debugging stuff or things taken from external projects. Thank you!

**Comment by bubnikv** [comment]
Sure thing. Will you do it, or shall I do it?
Thanks, Vojtech

**Comment by alexrj** [comment]
Better to do it before merging. Can you do it please? Thank you!

**Comment by alexrj** [comment]
Hello @bubnikv, this pull request contains too many different and unrelated changes. I cannot merge it this way.

Can we please separate the debugging visualization from the other things? Thank you!

**Comment by lordofhyphens** [comment]
@bubnikv Yeah, there's just too much going on with those commits; please rebase the visualization changes onto alexrj:master and update the PR (or submit a new one).

**Comment by lordofhyphens** [comment]
@bubnikv Are you planning to work on this, or can I close this PR until you have time to submit a new one? As @alexrj said we can't merge this in as it is.

**Comment by bubnikv** [comment]
I can look into this, but it is currently on the bottom of my list.
Vojtech

**Comment by lordofhyphens** [comment]
No hurry, as it is a debugging feature.

**Comment by lordofhyphens** [comment]
Since there is so much going on with that commit, going to close this PR. @bubnikv when you get the changes of interest teased out into their own branch please open a new PR.

This is definitely useful, but we cannot accept a PR that doesn't contain only the changes described.

**Pull request closed without merging**
