### PR TITLE
Addressed logic of enforced supports. 

### LINKED ISSUE #3836: Enforce Supports not functioning
Fresh build on April 2, 2017: 1.2.9-901-g90623c4
OS: Debian Stable

Description:
"Support material -> Enforce support for the first N layers" doesn't seem to do anything.
I have Supports disabled, then any number entered in the Enforce option.

If I'm understanding correctly, this would allow me to have supports generated for N layers, and the rest of my object (above that) be support-less.

### PR DESCRIPTION
**Pull request by jaggzh**
There are inconsistent rare crashes which I cannot find as related to my changes.

Fixes #3836

### CODE REVIEW

**Comment by lordofhyphens** [comment]
image

**Comment by lordofhyphens** [comment]
image
This is with 50 layers of enforced support.

**Comment by lordofhyphens** [comment]
I haven't been able to reproduce any of the crashes.

**Comment by alexrj** [comment]
The proposed changes make sense to me.

**Pull request merged**
