### PR TITLE
Added "Slice Now" menu item, which uses the functionality of send gcode.

### PR DESCRIPTION
**Pull request by lordofhyphens**
Simple fix for #2979 and #3071

### CODE REVIEW

**Comment by lordofhyphens** [comment]
I don't quite understand why I can't seemingly add a button to the side panel, but I am not entirely sure how wxperl works for that stuff.

**Comment by a4jp-com** [comment]
Maybe this button should be renamed "Reslice", unless the code stops all the slicing and you have to press this button for everything to be sliced.

**Comment by lordofhyphens** [comment]
Right now it just re-calls "export gcode" with a temporary file name.

**Comment by lordofhyphens** [comment]
Closing pull request, found a better way to do it.

**Pull request closed without merging**
