### PR TITLE
Localization and internationalization

### PR DESCRIPTION
**Pull request by linvswin**
I would like to add a support for  localization and internationalization. I've already made some changes and I 'd like to know what you think about. It's working in progress
thanks 
peppe

Volevo aggiungere il supporto alla localizzazione e internazionalizzazione. Ho gia fatto delle modifiche e vorrei sapere cosa ne pensate. It's working in progress
Grazie 
Peppe

### CODE REVIEW

**Comment by miguelangelcasanova** [comment]
Idem for a spanish translation.

**Comment by ttsuru** [comment]
:+1:

**Comment by lordofhyphens** [comment]
@linvswin I know it's been a while :) 

Would you be willing to rebase this onto the current master branch and update the PR? There's been some more text added too. Unfortunately, this wouldn't/can't be a one-time thing; someone needs to maintain all of these translations.

Any additional thoughts @alexrj ?

**Comment by lordofhyphens** [comment]
Upstream repo is dead, unfortunately can't use this anymore. 
I've added an i18n branch to Slic3r, please submit po files for that.

**Pull request closed without merging**
