### PR TITLE
Add fill pattern for aligned rectilinear fixes #3225

### LINKED ISSUE #3225: Feature Request - Disable Cross-Hatching Infill, and new Parallel Infill Pattern
Hello all. My name is Tiago, and I'm currently a Master student trying to optimize printing parameters to several filament materials, and I'm using Slic3r for the G-code generation.
As I am trying to create standard dog-bone test samples to test the material's mechanical properties, I came across a bit of a problem - I can't have cross-hatching infill, because to test the material to tensile stress, I need to have all infill aligned by the direction of tensile stress pull. By this, I mean that all lines of the infill (except near the perimeters) need to be aligned by the X axis, for example. 
You could even create a new infill pattern where the lines of the infill do not cross between layers, but instead, they could fill the gaps of infill lines beneath the active layer. This is a new idea of mine, a kind of Parallel Infill where all lines of the infill are parallel, at a given fill angle. This way you could get high density, with aligned inner structure.

For this same study, at the same time, I'll also need cross-hatched infill, rectilinear and others, but I also need several types of infill without being cross-hatched.
Besides trying to request a new feature to the program, I would like to ask you to indicate me a fast way to do this, by tweaking something, or by inputting some code in the command line, or by some sort of script of any kind.

Please, be kind to treat this issue as **urgent**, as for me and my colleagues, this is an real life urgent matter.

Best Regards,
Tiago Alves, from Portugal

### PR DESCRIPTION
**Pull request by forrestp**
Fixes #3225 with a new fill option called 'Aligned Rectilinear'

### CODE REVIEW

**Comment by lordofhyphens** [comment]
What is the purpose/need of this weaker infill pattern?

**Comment by lordofhyphens** [comment]
Looks like you posted something unrelated to the feature, this usually happens because you submitted the PR and then did work in the same branchor on something else. Can you pull those commits for the listed PR into their own branch and submit a new PR for this? 

We don't generally accept pull requests with unrelated changes in them.

**Comment by forrestp** [comment]
Sorry, closing this pull request and re-opening from a new branch.

**Comment by lordofhyphens** [comment]
Thanks, happens from time to time.

I usually do any new development from a fresh branch of master, or rebase
it onto master before pushing it for a PR.

**Pull request closed without merging**
