### PR TITLE
Pressure advance overrides print speeds patch

### PR DESCRIPTION
**Pull request by Sebastianv650**
This solves #3282. It resets the print speed after a advance/discharge and it checks if the speed is unchanged, but an advance has to be made because a discharge was done before.

Please note, this is my first own coding acitivity at github and I'm not familiar with perl, only a little bit of C. If some informations are missing for the request, please let me know!

### CODE REVIEW

**Comment by VanessaE** [comment]
This seems to eliminate the unexpectedly-fast print moves in the model I was testing with.  Speeds seem to be similar to what I had configured prior to enabling pressure advance.  One note though: the following warning appears on the controlling terminal when exporting g-code:

`Use of uninitialized value $oldSpeed in sprintf at /home/vanessa/RepRap/Slic3r-git-pressure/lib/Slic3r/GCode/PressureRegulator.pm line 86.`

**Comment by Sebastianv650** [comment]
@VanessaE, you might also have a look at https://github.com/MarlinFirmware/Marlin/pull/3676, this Marlin "extension" handles the nozzle pressure much better than it can be done inside a slicer. I wrote that code when I recognised that my prints are better with Slic3rs pressure control, but not perfect.

**Comment by VanessaE** [comment]
I'll pass but thanks for the suggestion.  Ultimately pressure advance wasn't what I needed, but at least your code seems to work. :smile:

**Comment by VanessaE** [comment]
This code seems to generally work, but with one glitch: as I approach the right amount of advance for my setup (common NEMA17 motor with MK8 hob, no extra gearing, B'struder drive block, feeding into 55cm of bowden tube), the extruder motor tends to skip a step at restart if there's a big enough change in flow rate from one retract to the next restart, or at least the behavior of the motor is very similar.

I have to wonder if it's appropriate to ramp the extruder speed up so quickly at the start of a layer.

My retract speed is usually at 200 mm/sec, with 5mm of retract length.

**Comment by Sebastianv650** [comment]
I assume you are speaking about the Slic3r feature and not the Marlin one.
200mm/s seems to be quite high in my eyes. Usual values I'm used to are around 40-70mm/s max. extruder speed. At last if you get skipped steps, your speed is to high.
Also have in mind that you can't exceed the mm³/s limit of your hot end for a pressure prime movement, which is the same as a printing move.

**Comment by VanessaE** [comment]
Hm.  I'll have to give it a try at the lower speed then.

Maybe it would be a good idea to add a setting for max speed of advance (at least forward)?

**Comment by lordofhyphens** [comment]
Isn't that covered by your max speed of the E axis?

**Comment by VanessaE** [comment]
You would be correct, were I trying to exceed the motor's max unloaded speed. :-) 

My motor presently has no gearing, so it's weaksauce even with a MK8 hob, but while extruding through the nozzle into free air, it can move the filament at about 7 mm/sec before it starts to skip steps.  I'm not sure one way or the other if the motor's having any problems at 200 mm/sec, but I don't hear it skipping steps when I'm not using pressure advance.

My Google-fu fails me today, so I'm not sure how that translates into actual printing speeds, but since a normal restart moves the same length of filament as the preceding retract, I wouldn't think there would be any significant load on the motor, regardless of retract speed.

**Comment by lordofhyphens** [comment]
With pressure advance it is deliberately overextruding for a brief period
to rebuild pressure. Odds are it is either too much, there is a bug in the
code (I don't know if the code/math matters if the flow units are mm^3 and
not mm for example), or your weaksauce motor will never be able to give you
the torque you want without some serious gearing work :(

**Comment by VanessaE** [comment]
Well I'm going to eventually do something about gearing, but as for the pressure advance, my point is that it should pressurize-after-restart at more normal print-like speeds, not at the retract speed.

**Comment by VanessaE** [comment]
Also bear in mind that Slic3r has a default speed of 40 mm/sec for retracts, which is still going to be far higher than a 0.4mm nozzle will allow for even with a huge gear reduction at the extruder.

**Comment by Sebastianv650** [comment]
Slic3r takes the retract speed for pressure advance lines, see here: https://github.com/alexrj/Slic3r/issues/3283
It's true that a pressure build up movement should have another speed value than normal retract, but same is true for nomal prime movements after a retract. A "unretract" at 40mm/s can only work due to the flex in the filament: During the retract, the half-molten filament gets streched and it will cool down. During the prime, the now longer (and thinner) filament is forced against the molten filament in the nozzle which can lead to skipped steps in special cases. Thats why FW retract in Marlin has a default prime speed of only 8mm/s.

**Comment by lordofhyphens** [comment]
We could add an option for a prime speed for advance, default it to 8mm/s

**Comment by VanessaE** [comment]
The problem that I was having with apparent skipped steps here seems to be resolved - I'm not sure a separate pressurize speed is needed now.  The cause was a clogged nozzle, but of an unusual enough nature that I simply had not begun to consider the possibility (more on that another time).  Meanwhile, my adventure with pressure advance continues: #3457

**Comment by alexrj** [comment]
Do you all agree this is mergeable? :-)

**Comment by VanessaE** [comment]
It was good last time I tried, however you need to make sure that it never generates speeds greater than what the user has already configured.  Related:  make sure wiping speed is similarly controlled.

**Comment by hexane360** [comment]
This has been generating the correct g-code for me. It definitely fixes the speed override problem. I don't see why any debate about the useability of Pressure Advance should affect this PR. The feature is currently in mainline Slic3r, it's just implemented incorrectly.

Regarding VanessaE's concerns, the code changes don't affect how Pressure Advance determines priming speeds. It only resets the feedrate after the extruder has been primed.

**Comment by lordofhyphens** [comment]
Mechanically it looks fine to me, and @hexane360 has a point here. I will squash and merge. If it all goes horrid, we can revert ;-)

**Pull request merged**
