### PR TITLE
Update 3D Honeycomb Infill to switch directions at squares rather than every line

### PR DESCRIPTION
**Pull request by gringer**
If the print alternates between horizontal and vertical at each square, it is able to print a fully-supported honeycomb structure with half as much filament and only sweeping through one direction. I was mostly there with the initial implementation of this code, but I needed to do some large octahedron printing myself to work out a better way to do it.

This modification reduces the need for bridging in the infill pattern (it only happens at the squares at the top and bottom of the print), which increases strength and reduces fill density.

see issue #4045 for more details.

FWIW, Slic3r has been much easier to hack than Cura2. Thanks for writing code that will compile somewhat easily on a Debian system.

### CODE REVIEW

**Comment by lordofhyphens** [comment]
I do my development work on Debian Jessie ;)

**Comment by lordofhyphens** [comment]
https://ci.appveyor.com/api/buildjobs/nrry2oeviolc396q/artifacts/Slic3r-master.2017.06.26.1250.aec1c3c.64bit.zip

Windows build of this PR.

**Comment by gringer** [comment]
This infill pattern seems to work better when I disable the bridge mode tweak and slightly reduce the infill speed. Otherwise, layers can pull the filament over from the layers underneath, creating a weaker (and less pretty) structure. Here's what it should look like:

https://twitter.com/gringene_bio/status/879932267954528256

**Comment by gringer** [comment]
For people interested in trying out this on their 3D printers before downloading/compiling, I've got a couple of Gcode models including this fill pattern on my Truncated Octahedron thingiverse page:

https://www.thingiverse.com/thing:2404685/

One model is a 50x50x25mm box with no side or top walls, which has proven to be fairly resistant to crushing (particularly in the centre).

The other model is a 40mm truncated octahedron with walls, so that the internal structure can be seen without having to think too hard.

**Comment by lordofhyphens** [comment]
On the windows build server there is an artifacts tab you can download
builds from

**Comment by lordofhyphens** [comment]
Thank you!

**Comment by lordofhyphens** [comment]
Also, sorry for taking forever to merge this.

**Pull request merged**
